# Generated by Django 4.0.1 on 2022-01-29 08:38

import article.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='分类名字')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='标签名字')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='文章简介')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='文章发布日期')),
                ('cover', models.URLField(default='http://pic.myh2o.top/defaultCover', max_length=128, verbose_name='封面图链接')),
                ('category', models.ForeignKey(blank=True, default=article.models.set_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.categories', verbose_name='文章分类')),
                ('tag', models.ManyToManyField(blank=True, to='article.Tags', verbose_name='文章标签')),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
    ]
