# Generated by Django 4.0.1 on 2022-02-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articles_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.URLField(default='https://pic.myh2o.top/defaultCover', max_length=300, verbose_name='封面图链接'),
        ),
    ]
