# Generated by Django 4.0.1 on 2022-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nick',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
