# Generated by Django 4.0.1 on 2022-01-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userinfo_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
